destination:
  server: https://kubernetes.default.svc

argocd:
  enabled: true
  targetRevision: dev-values-pt2
  extraValuesFiles: []
  valuesObject: {}

events:
  enabled: false
  targetRevision: dev-values-pt2
  extraValuesFiles: []
  valuesObject: {}

groups:
  enabled: true
  targetRevision: dev-values-pt2
  extraValuesFiles: []
  valuesObject: {}

kyverno:
  enabled: true
  targetRevision: 3.2.6
  extraValuesFiles: []
  valuesObject:
    admissionController:
      replicas: 3
      container:
        resources:
          limits:
            cpu: 2
            memory: 8Gi
          requests:
            cpu: 1
            memory: 4Gi
    backgroundController:
      extraArgs:
        genWorkers: 50
        clientRateLimitBurst: 500
        clientRateLimitQPS: 500
      replicas: 2
      resources:
        limits:
          cpu: 4
          memory: 32Gi
        requests:
          cpu: 2
          memory: 16Gi
    cleanupController:
      enabled: false
    reportsController:
      enabled: false

sessionspaces:
  enabled: true
  targetRevision: dev-values-pt2
  extraValuesFiles: []
  valuesObject: {}

sealedsecrets:
  enabled: true
  targetRevision: 2.16.0
  extraValuesFiles: []
  valuesObject: {}

workflows:
  enabled: true
  targetRevision: dev-values-pt2
  extraValuesFiles: []
  valuesObject: {}

graphProxy:
  enabled: true
  targetRevision: dev-values-pt2
  extraValuesFiles: []
  valuesObject: {}

dashboard:
  enabled: true
  targetRevision: dev-values-pt2
  extraValuesFiles: []
  valuesObject: {}
