argo-workflows:
  controller:
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 128Mi
  server:
    replicas: 1
    authModes: []
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 128Mi
  executor:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

ingresstlssecret:
  enabled: false
s3sealedsecret:
  enabled: false
bitnamisecret:
  enabled: false 

s3artifactpolicy:
  enabled: false
sessionspacepolicy:
  enabled: false
podgcpolicy:
  enabled: false
workflowlabelpolicy:
  enabled: false

postgresql-ha:
  postgresql:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  pgpool:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  persistence:
    storageClass: netapp
    size: 5Gi

  oauth2-proxy:
    enabled: false
  # replicaCount: 1
  # ingress:
  #   enabled: false
  # extraVolumes: []
  # extraVolumeMounts: []
  # alphaConfig:
  #   configData:
  #     providers: []
  redis:
    master:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
    replica:
      replicaCount: 0
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
