database:
  host: mysql://localhost:3306
  user: root
  password:
    value: rootpassword

mockDatabase:
  create: true

policy:
  create: false

serviceAccount:
  create: true

secret:
  create: false

deployment:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 512Mi
