global:
  database:
    create: true
    # Ignored if not mocking
    user: root
    password: rootpassword

policy:
  create: false

serviceAccount:
  create: false

secret:
  create: false

deployment:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 512Mi
