database:
  host: mysql://ispybdbproxy.diamond.ac.uk:4306/ispyb
  user: ispyb_ro
  password:
    secretName: ""
    secretKey: ""
ldapUrl: ldap://ldapmaster.diamond.ac.uk
requestRate: 1

image:
  repository: ghcr.io/diamondlightsource/workflows-sessionspaces
  pullPolicy: Always
  tag: ""

deployment:
  annotations: []
  podAnnotations: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  nodeSelector: {}
  affinity: {}
  tolerations: []

policy:
  create: true
  runAsUser: 36055

serviceAccount:
  create: true
  annotations: {}
  name: ""

secret:
  create: true

mockDatabase:
  create: false
  image:
    repository: ghcr.io/diamondlightsource/ispyb-database
    pullPolicy: Always
    tag: "v4.3.0"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi

nameOverride: ""
fullnameOverride: ""

