apiVersion: v2
name: ispyb 
description: Ispyb database deployment
type: application

version: 0.3.5
appVersion: 0.1.0-rc25
dependencies:
  - name: common
    version: 2.23.0
    repository: oci://docker.io/bitnamicharts
