database:
  host: mysql://localhost:3306
  dbPort: 3306
  user: root
  annotations: []
  image:
    repository: ghcr.io/diamondlightsource/ispyb-database
    pullPolicy: Always
    tag: "latest"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
